server:
  port: 9000
  servlet:
    context-path: /musicMatch
spring:
  profiles:
    active: dev
  application:
    name: music-match-service
  datasource:
    hikari:
      maximum-pool-size: 25
    url: jdbc:h2:file:./musicMatch-app;DB_CLOSE_ON_EXIT=TRUE
    platform: h2
    username: musicMatch
    password: musicMatch
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
        jdbc:
          time_zone: UTC-3
  ###
  #   H2 Settings
  ###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true
logging:
  file: musicMatch-service.log
paginacao:
    qtd_por_pagina: 100
openweathermap:
  key: "44e50b6fe6b867fb08afae593925409b"
spotify:
    clientId: f940676f484b42bca8218b4c0541048b
    clientSecret: 2e7cae388e2a47b5a9ffa8c228ddafea