INSERT INTO categoria (chave, nome) VALUES ('toplists','Top Lists');
INSERT INTO categoria (chave, nome) VALUES ('pop','Pop');
INSERT INTO categoria (chave, nome) VALUES ('hiphop','Hip-Hop');
INSERT INTO categoria (chave, nome) VALUES ('mood','Mood');
INSERT INTO categoria (chave, nome) VALUES ('workout','Workout');
INSERT INTO categoria (chave, nome) VALUES ('decades','Decades');
INSERT INTO categoria (chave, nome) VALUES ('blackhistorymonth','Black history is now');
INSERT INTO categoria (chave, nome) VALUES ('country','Country');
INSERT INTO categoria (chave, nome) VALUES ('focus','Focus');
INSERT INTO categoria (chave, nome) VALUES ('latin','Latin');
INSERT INTO categoria (chave, nome) VALUES ('chill','Chill');
INSERT INTO categoria (chave, nome) VALUES ('edm_dance','Dance/Electronic');
INSERT INTO categoria (chave, nome) VALUES ('rnb','R&B');
INSERT INTO categoria (chave, nome) VALUES ('rock','Rock');
INSERT INTO categoria (chave, nome) VALUES ('indie_alt','Indie');
INSERT INTO categoria (chave, nome) VALUES ('roots','Folk & Acoustic');
INSERT INTO categoria (chave, nome) VALUES ('party','Party');
INSERT INTO categoria (chave, nome) VALUES ('sleep','Sleep');
INSERT INTO categoria (chave, nome) VALUES ('classical','Classical');
INSERT INTO categoria (chave, nome) VALUES ('jazz','Jazz');
INSERT INTO categoria (chave, nome) VALUES ('inspirational','Christian');
INSERT INTO categoria (chave, nome) VALUES ('gaming','Gaming');
INSERT INTO categoria (chave, nome) VALUES ('romance','Romance');
INSERT INTO categoria (chave, nome) VALUES ('kpop','K-Pop');
INSERT INTO categoria (chave, nome) VALUES ('popculture','Pop culture');
INSERT INTO categoria (chave, nome) VALUES ('arab','Arab');
INSERT INTO categoria (chave, nome) VALUES ('desi','Desi');
INSERT INTO categoria (chave, nome) VALUES ('afro','Afro');
INSERT INTO categoria (chave, nome) VALUES ('metal','Metal');
INSERT INTO categoria (chave, nome) VALUES ('reggae','Reggae');
INSERT INTO categoria (chave, nome) VALUES ('soul','Soul');
INSERT INTO categoria (chave, nome) VALUES ('blues','Blues');
INSERT INTO categoria (chave, nome) VALUES ('punk','Punk');
INSERT INTO categoria (chave, nome) VALUES ('funk','Funk');
INSERT INTO categoria (chave, nome) VALUES ('dinner','Dinner');
INSERT INTO categoria (chave, nome) VALUES ('sessions','Spotify Singles');
INSERT INTO categoria (chave, nome) VALUES ('ellen','Ellen');
INSERT INTO categoria (chave, nome) VALUES ('travel','Travel');
INSERT INTO categoria (chave, nome) VALUES ('family','Kids & Family');
INSERT INTO categoria (chave, nome) VALUES ('comedy','Comedy');
INSERT INTO categoria (chave, nome) VALUES ('word','Word');